MENU_ITEMS = [
    {
        "id": 1,
        "name": "Masala Chai",
        "category": "chai",
        "description": "A classic, spiced Indian tea.",
        "price": 30,
        "available": True,
    },
    {
        "id": 2,
        "name": "Ginger Chai",
        "category": "chai",
        "description": "Masala chai with an extra kick of fresh ginger.",
        "price": 35,
        "available": True,
    },
    {
        "id": 3,
        "name": "Kulhad Chai",
        "category": "chai",
        "description": "Masala chai served in a traditional clay cup.",
        "price": 40,
        "available": False,
    },
    {
        "id": 4,
        "name": "Mathri",
        "category": "snacks",
        "description": "A crisp, flaky savory biscuit.",
        "price": 25,
        "available": True,
    },
    {
        "id": 5,
        "name": "Khari Biscuit",
        "category": "snacks",
        "description": "Light, layered puff pastry biscuit.",
        "price": 20,
        "available": True,
    },
    {
        "id": 6,
        "name": "Samosa",
        "category": "snacks",
        "description": "Deep-fried pastry with a spiced potato filling.",
        "price": 30,
        "available": False,
    },
    {
        "id": 7,
        "name": "Chai + Mathri Combo",
        "category": "combos",
        "description": "One Masala Chai paired with a plate of Mathri.",
        "price": 50,
        "available": True,
    },
    {
        "id": 8,
        "name": "Chai + Samosa Combo",
        "category": "combos",
        "description": "One Masala Chai paired with a Samosa.",
        "price": 55,
        "available": True,
    },
]
